### ISSUE TITLE
Which python version should we aim for?

### ISSUE THREAD

**Issue by balodja** [snad-space/coniferest#101]
We have 3.7 in the [pyproject.toml](https://github.com/snad-space/coniferest/blob/master/pyproject.toml), we have 3.8 in [tests](#95), we have 3.6 on the coin01 server. Yes, current coniferest package does not work on the coin01.

@hombit @matwey

**Comment by balodja** [comment]
I was wrong there are different python versions on coin01. But nevertheless I would like to be sure about coniferest depends.

**Comment by hombit** [comment]
We dropped 3.6 couple months ago because it is end-of-life (EOL) and modern packaging tooling doesn't support it anymore.

I've just dropped 3.7 testing in #95. I think we can also stop building wheels for 3.7, because it is close to its EOL and most of the packages we use finished supporting it in newer versions.
